# Generated by Django 5.1.5 on 2025-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='goal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
