# Generated by Django 5.1.6 on 2025-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='todoVideos'),
        ),
    ]
