# Generated by Django 5.1.6 on 2025-02-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todolist_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
