# Generated by Django 5.1.6 on 2025-02-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todolist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='profile',
        ),
    ]
